// <auto-generated />
using System;
using Board.ThirdPartyLibrary.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Board.ThirdPartyLibrary.Api.Persistence.Migrations
{
    [DbContext(typeof(BoardLibraryDbContext))]
    [Migration("20260301204029_Wave2StudiosMemberships")]
    partial class Wave2StudiosMemberships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("IdentityProvider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identity_provider");

                    b.Property<string>("KeycloakSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("keycloak_subject")
                        .HasComment("Immutable Keycloak subject identifier used as the durable external identity link.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("KeycloakSubject")
                        .IsUnique()
                        .HasDatabaseName("ux_users_keycloak_subject");

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("Application-owned identity projection linked to a Keycloak subject.");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.Studio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug")
                        .HasComment("Human-readable unique route key used for public studio pages.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_studios");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_studios_slug");

                    b.ToTable("studios", null, t =>
                        {
                            t.HasComment("Developer studios that own catalog content and related configuration.");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.StudioMembership", b =>
                {
                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid")
                        .HasColumnName("studio_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role")
                        .HasComment("Scoped role for the user within the studio.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("StudioId", "UserId")
                        .HasName("pk_studio_memberships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_studio_memberships_user_id");

                    b.ToTable("studio_memberships", null, t =>
                        {
                            t.HasComment("Studio-scoped memberships and roles owned by the application database.");

                            t.HasCheckConstraint("ck_studio_memberships_role", "role IN ('owner', 'admin', 'editor')");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.UserBoardProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("BoardUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("board_user_id")
                        .HasComment("Board-owned user identifier cached for application workflows.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<DateTime>("LinkedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_user_board_profiles");

                    b.HasIndex("BoardUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_board_profiles_board_user_id");

                    b.ToTable("user_board_profiles", null, t =>
                        {
                            t.HasComment("Optional cached linkage between an application user and a Board profile.");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.StudioMembership", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.Studio", "Studio")
                        .WithMany("Memberships")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_studio_memberships_studios_studio_id");

                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", "User")
                        .WithMany("StudioMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_studio_memberships_users_user_id");

                    b.Navigation("Studio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.UserBoardProfile", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", "User")
                        .WithOne("BoardProfile")
                        .HasForeignKey("Board.ThirdPartyLibrary.Api.Persistence.Entities.UserBoardProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_board_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", b =>
                {
                    b.Navigation("BoardProfile");

                    b.Navigation("StudioMemberships");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.Studio", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
