// <auto-generated />
using System;
using Board.ThirdPartyLibrary.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Board.ThirdPartyLibrary.Api.Persistence.Migrations
{
    [DbContext(typeof(BoardLibraryDbContext))]
    [Migration("20260304193808_Wave7UserProfileAvatar")]
    partial class Wave7UserProfileAvatar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("avatar_image_content_type");

                    b.Property<byte[]>("AvatarImageData")
                        .HasColumnType("bytea")
                        .HasColumnName("avatar_image_data");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentityProvider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identity_provider");

                    b.Property<string>("KeycloakSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("keycloak_subject")
                        .HasComment("Immutable Keycloak subject identifier used as the durable external identity link.");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("KeycloakSubject")
                        .IsUnique()
                        .HasDatabaseName("ux_users_keycloak_subject");

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("Application-owned identity projection linked to a Keycloak subject.");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("author_role");

                    b.Property<string>("Body")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MessageKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("message_kind");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_conversation_messages");

                    b.HasIndex("UserId");

                    b.HasIndex("ThreadId", "CreatedAtUtc")
                        .HasDatabaseName("ix_conversation_messages_thread_created_at");

                    b.ToTable("conversation_messages", null, t =>
                        {
                            t.HasComment("Persisted messages within generic workflow conversations.");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.ConversationMessageAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_conversation_message_attachments");

                    b.HasIndex("MessageId");

                    b.ToTable("conversation_message_attachments", null, t =>
                        {
                            t.HasComment("Binary attachments uploaded as part of persisted conversation messages.");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.ConversationThread", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_conversation_threads");

                    b.ToTable("conversation_threads", null, t =>
                        {
                            t.HasComment("Generic persisted conversation threads attached to workflow records.");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.DeveloperEnrollmentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid>("ConversationThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_thread_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastModeratorActionAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_moderator_action_at");

                    b.Property<Guid?>("LastModeratorActionByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_moderator_action_by_user_id");

                    b.Property<DateTime?>("ReapplyAvailableAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reapply_available_at");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status")
                        .HasComment("Current workflow status: pending_review, awaiting_applicant_response, approved, rejected, or cancelled.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_developer_enrollment_requests");

                    b.HasIndex("ConversationThreadId")
                        .IsUnique();

                    b.HasIndex("LastModeratorActionByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_developer_enrollment_requests_user_open_request")
                        .HasFilter("status IN ('pending_review', 'awaiting_applicant_response')");

                    b.HasIndex("UserId", "RequestedAtUtc")
                        .HasDatabaseName("ix_developer_enrollment_requests_user_requested_at");

                    b.ToTable("developer_enrollment_requests", null, t =>
                        {
                            t.HasComment("Application-owned developer enrollment workflow state for player accounts.");

                            t.HasCheckConstraint("ck_developer_enrollment_requests_status", "status IN ('pending_review', 'awaiting_applicant_response', 'approved', 'rejected', 'cancelled')");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.IntegrationConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json")
                        .HasComment("Provider-specific non-secret configuration values for the integration connection.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomPublisherDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("custom_publisher_display_name");

                    b.Property<string>("CustomPublisherHomepageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("custom_publisher_homepage_url");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("SupportedPublisherId")
                        .HasColumnType("uuid")
                        .HasColumnName("supported_publisher_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_integration_connections");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_integration_connections_organization_id");

                    b.HasIndex("SupportedPublisherId")
                        .HasDatabaseName("ix_integration_connections_supported_publisher_id");

                    b.ToTable("integration_connections", null, t =>
                        {
                            t.HasComment("Organization-owned reusable references to supported or custom external publishers/stores.");

                            t.HasCheckConstraint("ck_integration_connections_publisher_choice", "(supported_publisher_id IS NOT NULL AND custom_publisher_display_name IS NULL AND custom_publisher_homepage_url IS NULL) OR (supported_publisher_id IS NULL AND custom_publisher_display_name IS NOT NULL AND custom_publisher_homepage_url IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug")
                        .HasComment("Human-readable unique route key used for public organization pages.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_organizations_slug");

                    b.ToTable("organizations", null, t =>
                        {
                            t.HasComment("Developer organizations that own catalog content and related configuration.");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.OrganizationMembership", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role")
                        .HasComment("Scoped role for the user within the organization.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("OrganizationId", "UserId")
                        .HasName("pk_organization_memberships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_memberships_user_id");

                    b.ToTable("organization_memberships", null, t =>
                        {
                            t.HasComment("Organization-scoped memberships and roles owned by the application database.");

                            t.HasCheckConstraint("ck_organization_memberships_role", "role IN ('owner', 'admin', 'editor')");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.ReleaseArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("artifact_kind");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("package_name");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("VersionCode")
                        .HasColumnType("bigint")
                        .HasColumnName("version_code");

                    b.HasKey("Id")
                        .HasName("pk_release_artifacts");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_release_artifacts_release_id");

                    b.HasIndex("ReleaseId", "PackageName", "VersionCode")
                        .IsUnique()
                        .HasDatabaseName("ux_release_artifacts_release_id_package_name_version_code");

                    b.ToTable("release_artifacts", null, t =>
                        {
                            t.HasComment("Installable artifact metadata for title releases.");

                            t.HasCheckConstraint("ck_release_artifacts_artifact_kind", "artifact_kind IN ('apk')");

                            t.HasCheckConstraint("ck_release_artifacts_file_size_bytes", "file_size_bytes IS NULL OR file_size_bytes > 0");

                            t.HasCheckConstraint("ck_release_artifacts_version_code", "version_code > 0");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.SupportedPublisher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("HomepageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("homepage_url");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key")
                        .HasComment("Stable machine-friendly key for a supported publisher.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_supported_publishers");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_supported_publishers_key");

                    b.ToTable("supported_publishers", null, t =>
                        {
                            t.HasComment("Platform-managed canonical publisher registry entries available for developer acquisition connections.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAtUtc = new DateTime(2026, 3, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "itch.io",
                            HomepageUrl = "https://itch.io/",
                            IsEnabled = true,
                            Key = "itch-io",
                            UpdatedAtUtc = new DateTime(2026, 3, 2, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAtUtc = new DateTime(2026, 3, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Humble Bundle",
                            HomepageUrl = "https://www.humblebundle.com/",
                            IsEnabled = true,
                            Key = "humble-bundle",
                            UpdatedAtUtc = new DateTime(2026, 3, 2, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121212"),
                            CreatedAtUtc = new DateTime(2026, 3, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Game Jolt",
                            HomepageUrl = "https://gamejolt.com/",
                            IsEnabled = true,
                            Key = "game-jolt",
                            UpdatedAtUtc = new DateTime(2026, 3, 2, 20, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("content_kind");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentMetadataVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_metadata_version_id");

                    b.Property<Guid?>("CurrentReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_release_id");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("lifecycle_status")
                        .HasComment("Catalog lifecycle state used to control developer and public visibility.");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug")
                        .HasComment("Human-readable unique route key scoped to the owning organization.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visibility")
                        .HasComment("Public discoverability for routes and listing behavior.");

                    b.HasKey("Id")
                        .HasName("pk_titles");

                    b.HasIndex("CurrentReleaseId")
                        .HasDatabaseName("ix_titles_current_release_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_titles_organization_id");

                    b.HasIndex("CurrentMetadataVersionId", "Id");

                    b.HasIndex("CurrentReleaseId", "Id");

                    b.HasIndex("OrganizationId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_titles_organization_id_slug");

                    b.ToTable("titles", null, t =>
                        {
                            t.HasComment("Catalog titles owned by developer organizations.");

                            t.HasCheckConstraint("ck_titles_content_kind", "content_kind IN ('game', 'app')");

                            t.HasCheckConstraint("ck_titles_lifecycle_status", "lifecycle_status IN ('draft', 'testing', 'published', 'archived')");

                            t.HasCheckConstraint("ck_titles_visibility", "visibility IN ('private', 'unlisted', 'listed')");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleIntegrationBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcquisitionLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("acquisition_label");

                    b.Property<string>("AcquisitionUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("acquisition_url")
                        .HasComment("Player-facing acquisition URL for the title on the external publisher/store.");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json")
                        .HasComment("Provider-specific non-secret configuration values for the title binding.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IntegrationConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_connection_id");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_title_integration_bindings");

                    b.HasIndex("IntegrationConnectionId")
                        .HasDatabaseName("ix_title_integration_bindings_integration_connection_id");

                    b.HasIndex("TitleId")
                        .IsUnique()
                        .HasDatabaseName("ux_title_integration_bindings_title_id_primary_enabled")
                        .HasFilter("is_primary AND is_enabled");

                    b.ToTable("title_integration_bindings", null, t =>
                        {
                            t.HasComment("Title-scoped external acquisition bindings for supported or custom publishers/stores.");

                            t.HasCheckConstraint("ck_title_integration_bindings_primary_requires_enabled", "NOT is_primary OR is_enabled");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleMediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("alt_text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("MediaRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("media_role")
                        .HasComment("Fixed Board-style media slot such as card, hero, or logo.");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_url")
                        .HasComment("Absolute URL for the external media asset.");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_title_media_assets");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_title_media_assets_title_id");

                    b.HasIndex("TitleId", "MediaRole")
                        .IsUnique()
                        .HasDatabaseName("ux_title_media_assets_title_id_media_role");

                    b.ToTable("title_media_assets", null, t =>
                        {
                            t.HasComment("Fixed-slot Board-style media assets for catalog titles.");

                            t.HasCheckConstraint("ck_title_media_assets_dimensions", "(width IS NULL AND height IS NULL) OR (width > 0 AND height > 0)");

                            t.HasCheckConstraint("ck_title_media_assets_media_role", "media_role IN ('card', 'hero', 'logo')");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleMetadataVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgeRatingAuthority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("age_rating_authority")
                        .HasComment("Age rating authority such as ESRB or PEGI.");

                    b.Property<string>("AgeRatingValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("age_rating_value")
                        .HasComment("Authority-specific rating value such as E10+ or 12.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("GenreDisplay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("genre_display");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_frozen")
                        .HasComment("Whether the revision is immutable because the title has left draft or the revision has been preserved for history.");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("max_players");

                    b.Property<int>("MinAgeYears")
                        .HasColumnType("integer")
                        .HasColumnName("min_age_years");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("min_players");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number")
                        .HasComment("Per-title monotonically increasing metadata revision number.");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_title_metadata_versions");

                    b.HasAlternateKey("Id", "TitleId")
                        .HasName("ak_title_metadata_versions_id_title_id");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_title_metadata_versions_title_id");

                    b.HasIndex("TitleId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_title_metadata_versions_title_id_revision_number");

                    b.ToTable("title_metadata_versions", null, t =>
                        {
                            t.HasComment("Versioned player-facing catalog metadata snapshots for titles.");

                            t.HasCheckConstraint("ck_title_metadata_versions_min_age_years", "min_age_years >= 0");

                            t.HasCheckConstraint("ck_title_metadata_versions_player_counts", "min_players >= 1 AND max_players >= min_players");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MetadataVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("metadata_version_id");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("version")
                        .HasComment("Public semver release identifier.");

                    b.HasKey("Id")
                        .HasName("pk_title_releases");

                    b.HasAlternateKey("Id", "TitleId")
                        .HasName("ak_title_releases_id_title_id");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_title_releases_title_id");

                    b.HasIndex("MetadataVersionId", "TitleId");

                    b.HasIndex("TitleId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_title_releases_title_id_version");

                    b.ToTable("title_releases", null, t =>
                        {
                            t.HasComment("Semver releases associated with catalog titles.");

                            t.HasCheckConstraint("ck_title_releases_published_at", "(status = 'draft' AND published_at IS NULL) OR (status IN ('published', 'withdrawn') AND published_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_title_releases_status", "status IN ('draft', 'published', 'withdrawn')");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.UserBoardProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("BoardUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("board_user_id")
                        .HasComment("Board-owned user identifier cached for application workflows.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<DateTime>("LinkedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_user_board_profiles");

                    b.HasIndex("BoardUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_board_profiles_board_user_id");

                    b.ToTable("user_board_profiles", null, t =>
                        {
                            t.HasComment("Optional cached linkage between an application user and a Board profile.");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("action_url");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_notifications");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_user_notifications_user_created_at");

                    b.HasIndex("UserId", "IsRead", "CreatedAtUtc")
                        .HasDatabaseName("ix_user_notifications_user_is_read_created_at");

                    b.ToTable("user_notifications", null, t =>
                        {
                            t.HasComment("Generic in-app notifications targeted to local user projections.");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.ConversationMessage", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.ConversationThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_messages_threads");

                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", "User")
                        .WithMany("ConversationMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_messages_users");

                    b.Navigation("Thread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.ConversationMessageAttachment", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.ConversationMessage", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_message_attachments_messages");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.DeveloperEnrollmentRequest", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.ConversationThread", "ConversationThread")
                        .WithOne("DeveloperEnrollmentRequest")
                        .HasForeignKey("Board.ThirdPartyLibrary.Api.Persistence.Entities.DeveloperEnrollmentRequest", "ConversationThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_developer_enrollment_requests_conversation_threads");

                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", "LastModeratorActionByUser")
                        .WithMany("LastModeratedDeveloperEnrollmentRequests")
                        .HasForeignKey("LastModeratorActionByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_developer_enrollment_requests_last_moderator_users");

                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", "ReviewedByUser")
                        .WithMany("ReviewedDeveloperEnrollmentRequests")
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_developer_enrollment_requests_reviewed_by_users");

                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", "User")
                        .WithMany("DeveloperEnrollmentRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_developer_enrollment_requests_users");

                    b.Navigation("ConversationThread");

                    b.Navigation("LastModeratorActionByUser");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.IntegrationConnection", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.Organization", "Organization")
                        .WithMany("IntegrationConnections")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integration_connections_organizations_organization_id");

                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.SupportedPublisher", "SupportedPublisher")
                        .WithMany("IntegrationConnections")
                        .HasForeignKey("SupportedPublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_integration_connections_supported_publishers_supported_publisher_id");

                    b.Navigation("Organization");

                    b.Navigation("SupportedPublisher");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.OrganizationMembership", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.Organization", "Organization")
                        .WithMany("Memberships")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_organizations_organization_id");

                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", "User")
                        .WithMany("OrganizationMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_users_user_id");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.ReleaseArtifact", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleRelease", "Release")
                        .WithMany("Artifacts")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_artifacts_title_releases_release_id");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.Title", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.Organization", "Organization")
                        .WithMany("Titles")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_titles_organizations_organization_id");

                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleMetadataVersion", "CurrentMetadataVersion")
                        .WithMany()
                        .HasForeignKey("CurrentMetadataVersionId", "Id")
                        .HasPrincipalKey("Id", "TitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_titles_title_metadata_versions_current_metadata");

                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleRelease", "CurrentRelease")
                        .WithMany()
                        .HasForeignKey("CurrentReleaseId", "Id")
                        .HasPrincipalKey("Id", "TitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_titles_title_releases_current_release");

                    b.Navigation("CurrentMetadataVersion");

                    b.Navigation("CurrentRelease");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleIntegrationBinding", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.IntegrationConnection", "IntegrationConnection")
                        .WithMany("TitleIntegrationBindings")
                        .HasForeignKey("IntegrationConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_title_integration_bindings_integration_connections_integration_connection_id");

                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.Title", "Title")
                        .WithMany("IntegrationBindings")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_title_integration_bindings_titles_title_id");

                    b.Navigation("IntegrationConnection");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleMediaAsset", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.Title", "Title")
                        .WithMany("MediaAssets")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_title_media_assets_titles_title_id");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleMetadataVersion", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.Title", "Title")
                        .WithMany("MetadataVersions")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_title_metadata_versions_titles_title_id");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleRelease", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.Title", "Title")
                        .WithMany("Releases")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_title_releases_titles_title_id");

                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleMetadataVersion", "MetadataVersion")
                        .WithMany("Releases")
                        .HasForeignKey("MetadataVersionId", "TitleId")
                        .HasPrincipalKey("Id", "TitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_title_releases_title_metadata_versions_metadata");

                    b.Navigation("MetadataVersion");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.UserBoardProfile", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", "User")
                        .WithOne("BoardProfile")
                        .HasForeignKey("Board.ThirdPartyLibrary.Api.Persistence.Entities.UserBoardProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_board_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.UserNotification", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_notifications_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", b =>
                {
                    b.Navigation("BoardProfile");

                    b.Navigation("ConversationMessages");

                    b.Navigation("DeveloperEnrollmentRequests");

                    b.Navigation("LastModeratedDeveloperEnrollmentRequests");

                    b.Navigation("Notifications");

                    b.Navigation("OrganizationMemberships");

                    b.Navigation("ReviewedDeveloperEnrollmentRequests");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.ConversationMessage", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.ConversationThread", b =>
                {
                    b.Navigation("DeveloperEnrollmentRequest");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.IntegrationConnection", b =>
                {
                    b.Navigation("TitleIntegrationBindings");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.Organization", b =>
                {
                    b.Navigation("IntegrationConnections");

                    b.Navigation("Memberships");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.SupportedPublisher", b =>
                {
                    b.Navigation("IntegrationConnections");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.Title", b =>
                {
                    b.Navigation("IntegrationBindings");

                    b.Navigation("MediaAssets");

                    b.Navigation("MetadataVersions");

                    b.Navigation("Releases");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleMetadataVersion", b =>
                {
                    b.Navigation("Releases");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleRelease", b =>
                {
                    b.Navigation("Artifacts");
                });
#pragma warning restore 612, 618
        }
    }
}
