// <auto-generated />
using System;
using Board.ThirdPartyLibrary.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Board.ThirdPartyLibrary.Api.Persistence.Migrations
{
    [DbContext(typeof(BoardLibraryDbContext))]
    [Migration("20260301225254_Wave3TitlesMetadata")]
    partial class Wave3TitlesMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("IdentityProvider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identity_provider");

                    b.Property<string>("KeycloakSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("keycloak_subject")
                        .HasComment("Immutable Keycloak subject identifier used as the durable external identity link.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("KeycloakSubject")
                        .IsUnique()
                        .HasDatabaseName("ux_users_keycloak_subject");

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("Application-owned identity projection linked to a Keycloak subject.");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.Studio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug")
                        .HasComment("Human-readable unique route key used for public studio pages.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_studios");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_studios_slug");

                    b.ToTable("studios", null, t =>
                        {
                            t.HasComment("Developer studios that own catalog content and related configuration.");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.StudioMembership", b =>
                {
                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid")
                        .HasColumnName("studio_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role")
                        .HasComment("Scoped role for the user within the studio.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("StudioId", "UserId")
                        .HasName("pk_studio_memberships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_studio_memberships_user_id");

                    b.ToTable("studio_memberships", null, t =>
                        {
                            t.HasComment("Studio-scoped memberships and roles owned by the application database.");

                            t.HasCheckConstraint("ck_studio_memberships_role", "role IN ('owner', 'admin', 'editor')");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("content_kind");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentMetadataVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_metadata_version_id");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("lifecycle_status")
                        .HasComment("Catalog lifecycle state used to control developer and public visibility.");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid")
                        .HasColumnName("studio_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug")
                        .HasComment("Human-readable unique route key scoped to the owning studio.");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("visibility")
                        .HasComment("Public discoverability for routes and listing behavior.");

                    b.HasKey("Id")
                        .HasName("pk_titles");

                    b.HasIndex("StudioId")
                        .HasDatabaseName("ix_titles_studio_id");

                    b.HasIndex("CurrentMetadataVersionId", "Id");

                    b.HasIndex("StudioId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_titles_studio_id_slug");

                    b.ToTable("titles", null, t =>
                        {
                            t.HasComment("Catalog titles owned by developer studios.");

                            t.HasCheckConstraint("ck_titles_content_kind", "content_kind IN ('game', 'app')");

                            t.HasCheckConstraint("ck_titles_lifecycle_status", "lifecycle_status IN ('draft', 'testing', 'published', 'archived')");

                            t.HasCheckConstraint("ck_titles_visibility", "visibility IN ('private', 'unlisted', 'listed')");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleMetadataVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgeRatingAuthority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("age_rating_authority")
                        .HasComment("Age rating authority such as ESRB or PEGI.");

                    b.Property<string>("AgeRatingValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("age_rating_value")
                        .HasComment("Authority-specific rating value such as E10+ or 12.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("GenreDisplay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("genre_display");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_frozen")
                        .HasComment("Whether the revision is immutable because the title has left draft or the revision has been preserved for history.");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("max_players");

                    b.Property<int>("MinAgeYears")
                        .HasColumnType("integer")
                        .HasColumnName("min_age_years");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("min_players");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number")
                        .HasComment("Per-title monotonically increasing metadata revision number.");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_description");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid")
                        .HasColumnName("title_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_title_metadata_versions");

                    b.HasAlternateKey("Id", "TitleId")
                        .HasName("ak_title_metadata_versions_id_title_id");

                    b.HasIndex("TitleId")
                        .HasDatabaseName("ix_title_metadata_versions_title_id");

                    b.HasIndex("TitleId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_title_metadata_versions_title_id_revision_number");

                    b.ToTable("title_metadata_versions", null, t =>
                        {
                            t.HasComment("Versioned player-facing catalog metadata snapshots for titles.");

                            t.HasCheckConstraint("ck_title_metadata_versions_min_age_years", "min_age_years >= 0");

                            t.HasCheckConstraint("ck_title_metadata_versions_player_counts", "min_players >= 1 AND max_players >= min_players");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.UserBoardProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("BoardUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("board_user_id")
                        .HasComment("Board-owned user identifier cached for application workflows.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<DateTime>("LinkedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_user_board_profiles");

                    b.HasIndex("BoardUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_board_profiles_board_user_id");

                    b.ToTable("user_board_profiles", null, t =>
                        {
                            t.HasComment("Optional cached linkage between an application user and a Board profile.");
                        });
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.StudioMembership", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.Studio", "Studio")
                        .WithMany("Memberships")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_studio_memberships_studios_studio_id");

                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", "User")
                        .WithMany("StudioMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_studio_memberships_users_user_id");

                    b.Navigation("Studio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.Title", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.Studio", "Studio")
                        .WithMany("Titles")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_titles_studios_studio_id");

                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleMetadataVersion", "CurrentMetadataVersion")
                        .WithMany()
                        .HasForeignKey("CurrentMetadataVersionId", "Id")
                        .HasPrincipalKey("Id", "TitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_titles_title_metadata_versions_current_metadata");

                    b.Navigation("CurrentMetadataVersion");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.TitleMetadataVersion", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.Title", "Title")
                        .WithMany("MetadataVersions")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_title_metadata_versions_titles_title_id");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.UserBoardProfile", b =>
                {
                    b.HasOne("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", "User")
                        .WithOne("BoardProfile")
                        .HasForeignKey("Board.ThirdPartyLibrary.Api.Persistence.Entities.UserBoardProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_board_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.AppUser", b =>
                {
                    b.Navigation("BoardProfile");

                    b.Navigation("StudioMemberships");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.Studio", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("Board.ThirdPartyLibrary.Api.Persistence.Entities.Title", b =>
                {
                    b.Navigation("MetadataVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
